---
title: "Notes"
author: "IRC"
date: "17 February 2019"
output: html_document
---

## Data loading and cleaning

Keep data out of the git repo - exclude `./Data` in the `.gitignore`.

Cleaning

- read.csv("./Data/file.csv")
  - Doesn't work as not all columns have header
- Skip the column headers
- Convert first column to lubridate dates
  - Drop any rows without a valid date to get rid of a few rows with no valid data
- Some rows seem to have the column label incorporated eg "SpO2=000". 

## Graphing

`cowplot` ? for combining multiple plots
Need to set length of x to an hour for first and last plots

## To do

Functions for

- loading raw data from csv and cleaning
- adjusting time if device clock wasn't correct
- view length of data and drop unwanted times
- plot overall / summary oximetry & pulse
- plot hourly graphs
- calculate ODI

Report as a .rmd file?

## Calculating ODI

- start with peak of 0, desaturation of 0, max_dip 0
- whilst SpO2 == 0 move on
- SpO2 != 0 then
  - if SpO2 > peak then peak = SpO2 and trough = SpO2
  - if SpO2 < trough then trough = SpO2
  - if SpO2 < peak - 4 AND not already counted a desaturation then desaturation++
  - if SpO2 > trough + 4, clear count and set peak and trough = SpO2
  - if (peak - trough) > max_dip the max_dip = (peak - trough)
- make "4" a variable to allow different desaturation thresholds

Use interval length to calculate ODI, time with SpO2 == 0, etc